// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4xSbWjslyLaQZAcMREYZ0TQLGQIVeXQ',
    appId: '1:350609035141:web:cdd209a17fcdbca6d67eec',
    messagingSenderId: '350609035141',
    projectId: 'findfootball-d99d6',
    authDomain: 'findfootball-d99d6.firebaseapp.com',
    storageBucket: 'findfootball-d99d6.appspot.com',
    measurementId: 'G-XC3N2Z4216',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIB30JiK07LUDmgnC9YBz3uEf1sLS-7yg',
    appId: '1:350609035141:android:b76fd1e0f73aa4f1d67eec',
    messagingSenderId: '350609035141',
    projectId: 'findfootball-d99d6',
    storageBucket: 'findfootball-d99d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWK-5ZjawQuCq9PW9_A_NzPXE-VKufbck',
    appId: '1:350609035141:ios:3b16555291c273efd67eec',
    messagingSenderId: '350609035141',
    projectId: 'findfootball-d99d6',
    storageBucket: 'findfootball-d99d6.appspot.com',
    iosBundleId: 'uz.dasuty.findFootball',
  );
}
